set tool "quatcalc"
#set exp_internal 1
set arg1 "\[ 1 2 3 4 \]"
set arg2 "\[ 2 3 4 5 \]"

set testdata {
  {"+ $arg1 $arg2" "\\[ 3 5 7 9 \\]"}
  {"- $arg1 $arg2" "\\[ -1 -1 -1 -1 \\]"}
  {"* $arg1 $arg2" "\\[ -36 6 12 12 \\]"}
}

global QUATCALC
#    eval "spawn $QUATCALC $inputs"

foreach pattern $testdata {
    set inputs   [lindex $pattern 0]
    set expected [lindex $pattern 1]
#    puts "vals"
#    puts $inputs
#    puts $expected
#    set current_dir [pwd]
#    puts $current_dir
#    puts $QUATCALC
    puts "vals"
    puts "spawn $QUATCALC $inputs"
    eval "spawn $QUATCALC $inputs"
    expect {
         -re $expected {
            pass $pattern
        }
        default {
	    fail "$inputs $expected"
	}
    }
}
