#!/bin/sh

echo ""
echo "+"
./quatcalc '+' '[1 2 3 4]' '[5 6 7 8]'
./quatcalc '+' '[1 2 3 4]'

echo ""
echo "-"
./quatcalc '-' '[1 2 3 4]' '[5 6 7 8]'
./quatcalc '-' '[1 2 3 4]'

echo ""
echo "*"
./quatcalc '*' '[1 2 3 4]' '[5 6 7 8]'
./quatcalc '*' '[1 2 3 4]'  5
./quatcalc '*' '[1 2 3 4]'

echo ""
echo "/"
./quatcalc '/' '[1 2 3 4]' '[5 6 7 8]'
./quatcalc '/' '[1 2 3 4]'  5
./quatcalc '/' '[1 2 3 4]'

echo ""
echo "=="
./quatcalc '==' '[1 2 3 4]' '[1 2 3 4]'
./quatcalc '==' '[1 2 3 4]' '[5 6 7 8]'

echo ""
echo "!="
./quatcalc '!=' '[1 2 3 4]' '[1 2 3 4]'
./quatcalc '!=' '[1 2 3 4]' '[5 6 7 8]'

echo ""
echo "dot"
./quatcalc 'dot' '[1 2 3 4]' '[5 6 7 8]'

echo ""
echo "cross"
./quatcalc 'cross' '[1 2 3 4]' '[5 6 7 8]'

echo ""
echo "ang"
./quatcalc 'ang' '[1 2 3 4]' '[5 6 7 8]'

echo ""
echo "rot"
./quatcalc 'rot' '[1 2 3 4]' '[5 6 7 8]'
